# Generated by Django 4.0.2 on 2022-04-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('image_one', models.ImageField(upload_to='images')),
                ('image_two', models.ImageField(upload_to='images')),
                ('image_three', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
    ]
