# Generated by Django 4.0.3 on 2022-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
