# Generated by Django 4.0.3 on 2022-04-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_webpage', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='N/A'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(default='N/A'),
        ),
    ]
