# Generated by Django 4.0.3 on 2022-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_webpage', '0003_project_github_url_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.TextField(default='N/A'),
        ),
    ]
