# Generated by Django 4.0.3 on 2022-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_webpage', '0004_alter_project_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
