# Generated by Django 4.0.2 on 2022-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_webpage', '0005_alter_project_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('comment', models.TextField()),
            ],
        ),
    ]
